name: BSD
on: [push, pull_request]

jobs:
  freebsd:
    runs-on: macos-12
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        run: |
          pkg update
          pkg install -y autoconf automake bison flex pkgconf
          ./autogen.sh
          ./configure
          make
          make dist-xz
          make install
